### ISSUE TITLE
🐳[Feat] 호텔서비스/투숙 정보 수정

### ISSUE THREAD

**Issue by bucky1005** [1oT-organization/hotelity-backend#49]
# ⚠️ Issue
> 추가하려는 기능에 대해 간결하게 설명해주세요
- stayCode와 수정할 정보를 입력받아 해당 내역을 업데이트 하는 기능

# 📋 Details
> 기능 개발을 위해 어떤 작업을 수행할 것인지 자세히 설명해주세요.
- StayController에서 RequestBody로 받아온 데이터를 가공하여 StayService로 전달
- StayService에서 Entity와 값을 매칭시킴
- StayRepository에서 save()를 사용하여 해당 값을 저장

# ✏️ ToDoList
- [ ] 새로운 기능 구현 코드 작성
- [ ] 테스트 완료

# 🦉 관련 Issue
> 해당 기능과 관련된 이슈를 ex) #12 형태로 기재해주세요.

**Comment by mini-xi** [comment]
LocalDate 형식인 자료형 Date 형으로 수정, employeeCodeFk 자료형 String에서 Integer로 수정
