### ISSUE TITLE
🐳[Feat] 호텔관리/부대시설 등록

### ISSUE THREAD

**Issue by helloItsUniverse** [1oT-organization/hotelity-backend#63]
# ⚠️ Issue
> 지점 등록 기능

# 📋 Details
> 기능 개발을 위해 어떤 작업을 수행할 것인지 자세히 설명해주세요.
- RequestBody 에 내용을 입력받아 ancillary_tb에서 AncillaryRepository의 save()를 사용하여 부대시설 등록 수행
- HashMap() 사용하여 양식에 맞춰 ResponseEntity에 반환

# ✏️ ToDoList
- [ ] 새로운 기능 구현 코드 작성
- [ ] 테스트 완료

# 🦉 관련 Issue
> #60

**Comment by mini-xi** [comment]
부대시설 등록 기능 추가 완료
