### ISSUE TITLE
🐳[Feat] 호텔관리/부대시설 삭제

### ISSUE THREAD

**Issue by helloItsUniverse** [1oT-organization/hotelity-backend#70]
# ⚠️ Issue
> 부대시설 삭제 기능

# 📋 Details
> 기능 개발을 위해 어떤 작업을 수행할 것인지 자세히 설명해주세요.
- Pathvariable 에 삭제할 ancilllaryCode를 받아 ancillary_tb에서 AncillaryRepository의 deleteById()를 사용하여 객실 삭제 수행
- HashMap() 사용하여 양식에 맞춰 ResponseEntity에 반환

# ✏️ ToDoList
- [ ] 새로운 기능 구현 코드 작성
- [ ] 테스트 완료

# 🦉 관련 Issue
> #60 , #63 , #66

**Comment by mini-xi** [comment]
부대시설 삭제 기능 추가 완료
