### ISSUE TITLE
🐳[Feat] 고객/멤버십 발급 기능

### ISSUE THREAD

**Issue by bucky1005** [1oT-organization/hotelity-backend#77]
# ⚠️ Issue
> 추가하려는 기능에 대해 간결하게 설명해주세요
- 1년 단위로 결제 누적 금액을 산정하여 고객에게 멤버십을 일괄 발급하는 기능

# 📋 Details
> 기능 개발을 위해 어떤 작업을 수행할 것인지 자세히 설명해주세요.
- if문을 사용하여 1년간 누적 결제 금액 합산액을 기준으로 멤버십 등급을 나눔
- 누적 결제 금액 합산 시 결제 취소 여부를 확인하여 제외
- 올해 3월 이전 결제 내역의 취소 여부가 1로 변경되면 트리거를 사용하여 멤버십을 등급을 재산정
- 멤버십 등급 재산정 시 멤버십 등급에 변화가 있을 경우 발급된 멤버십 쿠폰을 취소 후 재발급

# ✏️ ToDoList
- [ ] 새로운 기능 구현 코드 작성
- [ ] 테스트 완료

# 🦉 관련 Issue
> 해당 기능과 관련된 이슈를 ex) #12 형태로 기재해주세요.

**Comment by mini-xi** [comment]
멤버십 발급 기능 추가 완료
